# Generated by Django 4.1.7 on 2023-02-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='desc',
            field=models.CharField(default='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='events',
            name='etime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='stime',
            field=models.DateTimeField(null=True),
        ),
    ]
